name: content to Pages

on:
  push:
    branches: ["staging"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    - name: Build firmware
      working-directory: .
      run: pio run -e nodemcuv2
    - name: Build fs
      working-directory: .
      run: pio run -t buildfs -e nodemcuv2

    - name: Rename and move bins
      run: |
        mkdir bins
        mv .pio/build/nodemcuv2/firmware.bin bins/nodemcuv2-fw.bin
        mv .pio/build/nodemcuv2/littlefs.bin bins/nodemcuv2-fs.bin


  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: ls
        run: |
          ls 
          ls .pio
          ls .pio/build
          ls bins
      - name: copy bins
        run: |
          cp bins/*.bin ./uploader/firmware
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: './uploader'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
